name: maps_toolkit
description: Maps toolkit - different geo-measurements utils - area of polygon, distance between point, heading and offset between points (port of SphericalUtil from Java-library `android-maps-utils`).
version: 1.0.1+1
homepage: https://github.com/kb0/maps_toolkit/
author: Kirill Bychkov <bychkov.kirill.0@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  pedantic: ^1.8.0

dev_dependencies:
  test: ^1.6.5
