name: maps_toolkit
description: Maps toolkit - geo-measurements utils - area of polygon, distance between point, heading and offset between points (port of SphericalUtil, PolyUtil from `android-maps-utils`).
version: 1.1.0+2
homepage: https://github.com/kb0/maps_toolkit/

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:

dev_dependencies:
  test: any
  pedantic: '>=1.8.0 <3.0.0'
